### ISSUE TITLE
So much slower.

### ISSUE THREAD

**Issue by destructor465** [ThelDoctor/PCGSharp#3]
Hi, I would like to know why this RNG is so much slower than System.RNG, by using following code:
`Stopwatch timer = new Stopwatch();
            Random rng = new Random();
            PcgExtended pcg = PcgExtended.Default;

            // Warm up
            for (int i = 0; i < 1000000; i++)
                rng.NextDouble();

            for (int i = 0; i < 1000000; i++)
                pcg.NextFloat();

            Console.WriteLine("Generating 1,000,000 random numbers:");
            Console.WriteLine("System.Random:");
            timer.Start();

            for (int i = 0; i < 1000000; i++)
                rng.Next();

            Console.WriteLine("Next: " + timer.ElapsedMilliseconds + " ms.");
            timer.Restart();

            for (int i = 0; i < 1000000; i++)
                rng.NextDouble();

            Console.WriteLine("NextDouble: " + timer.ElapsedMilliseconds + " ms.");
            timer.Restart();
            //////////////////////////////////////////////////
            Console.WriteLine();

            Console.WriteLine("PCG:");

            for (int i = 0; i < 1000000; i++)
                pcg.Next();

            Console.WriteLine("Next: " + timer.ElapsedMilliseconds + " ms.");
            timer.Restart();

            for (int i = 0; i < 1000000; i++)
                pcg.NextDouble();

            Console.WriteLine("NextDouble: " + timer.ElapsedMilliseconds + " ms.");
            timer.Restart();

            for (int i = 0; i < 1000000; i++)
                pcg.NextFloat();

            Console.WriteLine("NextFloat: " + timer.ElapsedMilliseconds + " ms.");
            timer.Restart();

            for (int i = 0; i < 1000000; i++)
                pcg.NextByte();

            Console.WriteLine("NextByte: " + timer.ElapsedMilliseconds + " ms.");
            timer.Restart();

            timer.Stop();
            Console.WriteLine();`

I got these results:
System.Random:
Next: ~10ms.
NextDouble: ~10ms.

Pcg:
Next: ~40ms.
NextDouble: ~50ms.
NextFloat: ~50ms.
NextByte: ~50ms.

By ~ I mean +/- 10 ms.
I would like to know if this is correct and it's really this slow or just I doing something wrong?

**Comment by OracPrime** [comment]
I suspect you are running a debug build?  Running the same code as you in release build (outside of the IDE), I get PcG about the same speed for Next and about 30% slower for NextDouble.  If however I upgrade the PcG project to .Net 4.7 and put a     [MethodImpl(MethodImplOptions.AggressiveInlining)]
on NextDouble then it becomes faster than System.Random:
Generating 10,000,000.00 random numbers:
System.Random:
Next: 93 ms.
NextDouble: 113 ms.

PCG:
Next: 77 ms.
NextDouble: 76 ms.
NextFloat: 215 ms.
NextByte: 76 ms.


You can see the effect of inlining, as I didn't use the aggressive inline attribute for NextFloat.  Note that I went up to 10 million numbers to get measurable times.

**Comment by OracPrime** [comment]
In fact if you switch to 64bit so that RyuJIT kicks in, and things get even faster:
Generating 10,000,000.00 random numbers:
System.Random:
Next: 79 ms.
NextDouble: 77 ms.

PCG:
Next: 32 ms.
NextDouble: 32 ms.
NextFloat: 66 ms.
NextByte: 33 ms.

**Comment by destructor465** [comment]
Oh I see, release build works a lot better for me, thanks for response.
